/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   tokenizer_tests.h                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: advorace <advorace@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/19 15:53:24 by advorace          #+#    #+#             */
/*   Updated: 2026/05/19 18:06:18 by advorace         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#pragma once

#include <stddef.h>

typedef struct s_tokenize_tests
{
    char    *token;
    int     number_of_tokens;    
} t_tokenize_tests;

t_tokenize_tests tokenize_tests[] = {
    {"cd ", 1},
    {"cd ..", 2},
    {"cd .", 2},
    {"cd /Users ", 2},
    {"cd // ", 2},
    {"cd '//' ", 2},
    {"cd ////// ", 2},
    {"cd ./././ ", 2},
    {"cd /", 2},
    {"cd '/////' 2>/dev/null ", 5},
    {"cd '/etc' ", 2},
    {"cd '/var' ", 2},
    {"cd \"doesntexist\" ", 2},
    {"cd ../../..", 2},
    {"cd \"wtf\" 2>/dev/null ", 5},
    {"cd .. ", 2},
    {"cd ..", 2},
    {"cd ?", 2},
    {"cd +", 2},
    {"cd _", 2},
    {"$A", 1},
    {"echo $SHLVL", 2},
    {"echo $USER$12USER$USER=4$USER12", 2},
    {"echo $USER $123456789USER $USER123456789", 4},
    {"echo $USER $9999USER $8888USER $7777USER", 5},
    {"echo $USER $USER9999 $USER8888 $USER7777", 5},
    {"echo $USER $USER9999 $USER8888 $USER7777 \"$USER\"", 6},
    {"export $? ", 2},
    {"export TEST", 2},
    {"export TEST=", 2},
    {"export TEST=123", 2},
    {"export ___TEST=123", 2},
    {"export --TEST=123", 2},
    {"export \"\"=\"\"", 2},
    {"export ''=''", 2},
    {"export \"=\"=\"=\"", 2},
    {"export '='='='", 2},
    {"export TE\\ST=100", 2},
    {"export TE-ST=100", 2},
    {"export -TEST=100", 2},
    {"export TEST-=100", 2},
    {"export _TEST=100", 2},
    {"export | grep \"SHLVL\"", 4},
    {"export TEST", 2},
    {"export ==========", 2},
    {"export 1TEST=", 2},
    {"export TEST", 2},
    {"export \"\"=\"\"", 2},
    {"export TES=T=\"\"", 2},
    {"export TE+S=T=\"\"", 2},
    {"export TES\\T=123", 2},
    {"export TES.T=123", 2},
    {"export TES\\$T=123", 2},
    {"export TES\\T", 2},
    {"export TES.T=123", 2},
    {"export TES+T=123", 2},
    {"export TES=T=123", 2},
    {"export TES}T=123", 2},
    {"export TES{T=123", 2},
    {"export TES-T=123", 2},
    {"export -TEST=123", 2},
    {"export _TEST=123", 2},
    {"export TES_T=123", 2},
    {"export TEST_=123", 2},
    {"export TE*ST=123", 2},
    {"export TES#T=123", 2},
    {"export TES@T=123", 2},
    {"export TES!T=123", 2},
    {"export TES$?T=123", 2},
    {"export =============123", 2},
    {"export +++++++=123", 2},
    {"export ________=123", 2},
    {"export export", 2},
    {"env | grep \"SHLVL\"", 4},
    {"echo oui | cat -e", 5},
    {"echo oui | echo non | echo something | grep oui", 11},
    {"echo oui | echo non | echo something | grep non", 11},
    {"echo oui | echo non | echo something | grep something", 11},
    {"cd .. | echo \"something\"", 5},
    {"cd .. | echo \"something\"", 5},
    {"cd / | echo \"something\"", 5},
    {"ifconfig | grep \":\"", 4},
    {"ifconfig | grep nothing", 4},
    {"whoami | grep $USER", 4},
    {"whoami | grep $USER > tmp/file", 6},
    {"whoami | cat -e | cat -e > tmp/file ", 9},
    {"cat Makefile | grep \"FLAGS\"", 5},
    {"cat Makefile | cat -e | cat -e", 8},
    {"cat Makefile | grep \"FLAGS\" | grep \"FLAGS\" | cat -e", 11},
    {"export TEST=123 | cat -e | cat -e", 8},
    {"unset TEST | cat -e", 5},
    {"echo test | cat -e | cat -e | cat -e", 11},
    {"whereis ls | cat -e | cat -e > test", 10},
    {"echo test | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e | cat -e", 62},
    {"ls -l | grep \".\"", 5},
    {"whereis grep > tmp/file ", 4},
    {"whereis grep > tmp/file", 4},
    {"ls -l > tmp/file", 4},
    {"ls -l > tmp/file", 4},
    {"unset PATH ", 2},
    {"unset TES\\T", 2},
    {"unset TES;T", 2},
    {"unset TES.T", 2},
    {"unset TES+T", 2},
    {"unset TES=T", 2},
    {"unset TES}T", 2},
    {"unset TES{T", 2},
    {"unset TES-T", 2},
    {"unset -TEST", 2},
    {"unset _TEST", 2},
    {"unset TES_T", 2},
    {"unset TEST_", 2},
    {"unset TE*ST", 2},
    {"unset TES#T", 2},
    {"unset TES@T", 2},
    {"unset TES!T", 2},
    {"unset TES$?T", 2},
    {"unset ============", 2},
    {"unset +++++++", 2},
    {"unset ________", 2},
    {"unset export", 2},
    {"unset echo", 2},
    {"unset cd", 2},
    {"unset unset", 2},
    {"unset TES^T", 2},
    {"unset TES!T", 2},
    //{"unset TES\~T", 2},
    {"\"   \"", 1},
    {"'   '", 1},
    {"'                           ", 1},
    {"\"                            ", 1},
    {"\"   \"   \"   \"", 2},
    {"\"   \"", 1},
    {"\"   \"", 1},
    {"'   '   '   '", 2},
    {"'   '", 1},
    {"' a  '", 1},
    {"  a   ", 1},
    {"\" a  \"", 1},
    {"' a  '", 1},
    {"  a           ", 1},
    {"'     a                     ", 1},
    {"\"     a                      ", 1},
    {"\" a  \"   \"   \"", 2},
    {"\" a  \"", 1},
    {"\" a  \"", 1},
    {"' a  '   '   '", 2},
    {"' a  '", 1},
    {"' a  '", 1},
    {"     ", 0},
    {"\"   \"", 1},
    {"'   '", 1},
    {"a              ", 1},
    {"a '                         ", 2},
    {"a \"                          ", 2},
    {"a \"   \"   \"   \"", 3},
    {"a \"   \"", 2},
    {"a \"   \"", 2},
    {"a '   '   '   '", 3},
    {"a '   '", 2},
    {"a '   '", 2},
    {"|", 1},
    {"    |", 1},
    {"|    ", 1},
    {"a  |", 2},
    {"|  A", 2},
    {"echo_abc", 1},
    {"echo abc \"    \" | cat -e", 6},
    {NULL, 0}
};